#Header
Header header


#Status of the Manager of Actions
int32 status



#Predefined status
int32 TAKINGOFF			                = 1
int32 HOVERING			                = 2
int32 LANDING 			                = 3
int32 LANDED           		          = 4
int32 SLEEPING                      = 5
#int32 ABORT_LANDING_AND_TAKE_OFF   = 6
int32 MOVING_MANUAL_ALTITUD         = 7
int32 MOVING_MANUAL_THRUST          = 8
int32 MOVING_POSITION               = 9
int32 MOVING_SPEED                  = 10
int32 MOVING_TRAJECTORY             = 11
int32 MOVING_VISUAL_SERVOING        = 12
int32 HOVERING_VISUAL_SERVOING      = 13
int32 EMERGENCY                     = 14
int32 MOVING_FLIP                   = 15
int32 MOVING_FLIP_RIGHT             = 16
int32 MOVING_FLIP_LEFT              = 17
int32 MOVING_FLIP_FRONT             = 18
int32 MOVING_FLIP_BACK              = 19
int32 MOVING_EMERGENCY              = 20
int32 LANDING_AUTONOMOUS            = 21
int32 MOVE_VISUAL_SERVOING_RL       = 22
int32 UNKNOWN                       = 100
