# SERVICE TYPE: AddBelief
# ------------------------------------------------------------------------------
# This service adds a belief expression to the belief memory

bool multivalued          # whether to keep clashing beliefs in the memory or not
string belief_expression  # belief expression to add to the memory
---
bool success              # whether the belief has been added successfully or not
# ------------------------------------------------------------------------------
