# This service returns the list of behaviors that can be activated in a reactive way

BehaviorCommand[] reactive_behaviors          # Contains every reactive behavior available (with high ir low priority)
BehaviorCommand[] active_behaviors            # Contains every deliberative behavior
---
BehaviorCommand[] high_priority_behaviors     # Returns every behavior that can be activated in a reactive way (with high priority)
BehaviorCommand[] low_priority_behaviors      # Returns every behavior that can be activated in a reactive way (with low priority)
bool ack                                      # If this value is true, the operation was done succesfully
string error_message                          # If the above variable is false, an error is contained inside this variable
