# SERVICE TYPE: RemoveBelief
# ------------------------------------------------------------------------------
# This service removes a belief expression from the belief memory

string belief_expression  # belief expression to remove from the memory
---
bool success              # whether the belief has been removed successfully or not
# ------------------------------------------------------------------------------
