#! /bin/bash

cd $DRONE_STACK
source setup.sh

#Ejecucion
rosmake driverPelicanROSModule driver_px4flow_interface_ROSModule driver_camera_ueye_ROSModule droneMidLevelAutopilotROSModule droneEKFStateEstimatorROSModule droneTrajectoryControllerROSModule droneComputerVisionIARC14ROSModule droneIARC14BrainROSModule droneIARC14MissionSchedulerROSModule droneCV2DTo3DROSModule droneTrajectoryPlannerROSModule droneMissionPlannerROSModule droneInterfaceROSModule droneLoggerROSModule droneSimulatorRvizROSModule dronePelicanSimulatorROSModule droneSimulatorGridROSModule droneEkfSimulatorRvizROSModule robotSimulatorRvizROSModule droneSimulatoriRobotCVROSModule robotSimulatorRvizROSModule

# droneTrajectoryPlannerROSModule droneMissionPlannerROSModule
# rosmake droneTrajectoryPlannerROSModule droneMissionPlannerROSModule

# Interfaces extra
# rosmake droneInterfaceROSModule

# Logging extra
# rosmake droneLoggerROSModule

#Simulacion extra
# rosmake droneSimulatorRvizROSModule dronePelicanSimulatorROSModule droneSimulatorGridROSModule droneEkfSimulatorRvizROSModule robotSimulatorRvizROSModule droneSimulatoriRobotCVROSModule robotSimulatorRvizROSModule
