function [ mission_text ] = mission_opening( mission_name, prec_x, prec_y, prec_z, prec_yaw)
%MISSION_OPENING Summary of this function goes here
%   Detailed explanation goes here

mission_text = ...
['<?xml version="1.0"?>\n', ... 
'<mission description="',mission_name,'">\n', ... 
	'\t<config>\n', ... 
		'\t\t<precission>\n', ... 
			'\t\t\t<x>',num2str(prec_x),'</x>\n', ... 
			'\t\t\t<y>',num2str(prec_y),'</y>\n', ... 
			'\t\t\t<z>',num2str(prec_z),'</z>\n', ... 
			'\t\t\t<yaw>',num2str(prec_yaw),'</yaw> <!--deg-->\n', ... 
		'\t\t</precission>\n', ... 
	'\t</config>\n'];

end

