function [ mission_text ] = sleep_time( id_num, sleep_time)
%LAND_SUBMISSION Summary of this function goes here
%   Detailed explanation goes here

mission_text = ...
	['\t<submission description="N - sleep, land">\n', ... 
		'\t\t<config>\n', ... 
			'\t\t\t<id>',num2str(id_num),'</id>\n', ... 
		'\t\t</config>\n', ... 
		'\t\t<task description=".2 - sleep for at least 1 secs">\n', ... 
			'\t\t\t<config>\n', ... 
				'\t\t\t\t<id>02</id>\n', ... 
				'\t\t\t\t<time>',num2str(sleep_time),'</time>\n', ... 
			'\t\t\t</config>\n', ... 
			'\t\t\t<command>sleep</command>\n', ... 
		'\t\t</task>\n', ...		
	'\t</submission>\n'];
end

