export AEROSTACK_WS_PATH="$HOME/workspace/ros/aerostack_catkin_ws"
export AEROSTACK_STACK_SUBPATH="aerostack_stack"
export ROS_DISTRO="kinetic"
export AEROSTACK_WORKSPACE="$AEROSTACK_WS_PATH"
export AEROSTACK_STACK="$AEROSTACK_WS_PATH/src/$AEROSTACK_STACK_SUBPATH"
export ROTORS_SIMULATOR_PATH=$AEROSTACK_STACK/stack/simulation_system/drone_simulator/rotors_simulator_gazebo/rotors_simulator

########## uncomment theese for pixhawk_sitl and comment the rotorS ones
# Set the plugin path so Gazebo finds our model and sim
# export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$HOME/src/pixhawk_sitl/sitl_gazebo/Build
# Set the model path so Gazebo finds the airframes
# export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:$HOME/src/pixhawk_sitl/sitl_gazebo/models
# Disable online model lookup since this is quite experimental and unstable
# export GAZEBO_MODEL_DATABASE_URI=""

########## uncomment theese for rotorS and comment the pixhawk_sitl ones 
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:$ROTORS_SIMULATOR_PATH/rotors_gazebo_plugins
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:$ROTORS_SIMULATOR_PATH/rotors_gazebo/models

########## todo: custom models from mounted path ~/gazebo_ws/models

set +e
