" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
syntax on

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Provides Monokai
Plugin 'crusoexia/vim-monokai'
" Autocompletion on tab
Plugin 'https://github.com/vim-scripts/AutoComplPop'
call vundle#end()            " required

set expandtab
set shiftwidth=2
set softtabstop=2
filetype plugin indent on

colorscheme monokai
set t_Co=256

set number

nnoremap <C-Right> gT
nnoremap <C-Left> gT

" powerline settings
set laststatus=2
set term=xterm-256color
set termencoding=utf-8

set history=50    " keep 50 lines of command line history
set ruler   " show the cursor position all the time
set showcmd   " display incomplete commands
set incsearch   " do incremental searching
"set autoindent   " always set autoindenting on
set foldmethod=indent

" allow mouse interaction
set mouse=n

set undodir=~/.vim/undo//
set directory=~/.vim/swap//
set backupdir=~/.vim/backup//

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup    " do not keep a backup file, use versions instead
else
  set backup    " keep a backup file (restore to previous version)
  set undofile    " keep an undo file (undo changes after closing)
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  set hlsearch
endif


if has('langmap') && exists('+langnoremap')
  " Prevent that the langmap option applies to characters that result from a
  " mapping.  If unset (default), this may break plugins (but it's backward
  " compatible).
  set langnoremap
endif

" more natural splits
set splitbelow
set splitright
